image: Ubuntu

environment:
  nodejs_version: "12"

stack: node 12

branches:
  except:
    - gh-pages

skip_tags: true

max_jobs: 1

install:
  - node --version
  - yarn --version
  - yarn
  - yarn bootstrap

build_script:
  - yarn build

before_test:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

test_script:
  - yarn test

after_test:
  - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
  - ./cc-test-reporter after-build

deploy_script:
  - npx -p @qiwi/semrel-toolkit multi-semrel

