image: Ubuntu
branches:
  except:
    - gh-pages

cache:
  - node_modules -> appveyor.yml, package.json, yarn.lock

skip_tags: true
max_jobs: 2
matrix:
  fast_finish: true

init:
  - cmd: powershell Install-Product node $env:nodejs_version
  - sh: nvm install $nodejs_version
  - node --version
  - yarn --version

install:
  - apt-get -y install jq
  - echo "install"

environment:
  nodejs_version: "14"
  matrix:
    - job_name: Build
      job_group: Build
      STAGE: build

    - job_name: TestNodeJS14
      job_group: Tests
      job_depends_on: Build
      STAGE: testnodejs14

    - job_name: TestNodeJS12
      job_group: Tests
      job_depends_on: Build
      nodejs_version: "12"
      STAGE: testnodejs12

    - job_name: Deploy
      job_depends_on: Tests
      STAGE: deploy

for:
  - matrix:
      only:
        - job_name: Build
    build_script:
      - 7z a artifact.zip README.md packages/*/target packages/*/docs packages/*/flow-typed packages/*/typings
      - # appveyor PushArtifact artifact.zip
    artifacts:
      - path: artifact.zip
        name: artifact

  - matrix:
      only:
        - branch: master
        - job_name: TestNodeJS12

    before_test:
      - appveyor SetVariable -Name ARTIFACT_JOB -Value $(curl https://ci.appveyor.com/api/projects/QIWI/masker/builds/$APPVEYOR_BUILD_ID | jq -r '.build.jobs[0].jobId')
      - appveyor DownloadFile "https://ci.appveyor.com/api/buildjobs/$ARTIFACT_JOB/artifacts/artifact.zip"
      - 7z x artifact.zip -y

    test_script:
      - yarn test

  - matrix:
      only:
        - job_name: TestNodeJS14

    before_test:
      - appveyor SetVariable -Name ARTIFACT_JOB -Value $(curl https://ci.appveyor.com/api/projects/QIWI/masker/builds/$APPVEYOR_BUILD_ID | jq -r '.build.jobs[0].jobId')
      - appveyor DownloadFile "https://ci.appveyor.com/api/buildjobs/$ARTIFACT_JOB/artifacts/artifact.zip"
      - 7z x artifact.zip -y
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
    test_script:
      - yarn test:report
    after_test:
      - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
      - sh: |
          if [ "$APPVEYOR_PULL_REQUEST_NUMBER" = "" ]; then
              ./cc-test-reporter after-build -r ${CC_TEST_REPORTER_ID}
          fi

  - matrix:
      only:
        - APPVEYOR_PULL_REQUEST_NUMBER: ''
        - job_name: Deploy
        - branch: master

    deploy_script:
      - appveyor DownloadFile "https://ci.appveyor.com/api/projects/qiwi/masker/artifacts/artifact.zip?job=Build"
      - 7z x artifact.zip -y
      - npx -p @qiwi/semrel-toolkit multi-semrel
