image: Ubuntu
branches:
  except:
    - gh-pages

cache:
  - node_modules -> appveyor.yml, package.json, yarn.lock

skip_tags: true
max_jobs: 2
matrix:
  fast_finish: true

init:
  - cmd: powershell Install-Product node $env:nodejs_version
  - sh: nvm install $nodejs_version
  - node --version
  - yarn --version

install:
  - yarn --ignore-engines
  - yarn bootstrap

environment:
  nodejs_version: "14"
  matrix:
    - job_name: TestNodeJS14
      job_group: Tests

    - job_name: TestNodeJS12
      job_group: Tests
      nodejs_version: "12"

    - job_name: Deploy
      job_depends_on: Tests

for:
  - matrix:
      only:
        - branch: master
        - job_name: TestNodeJS12
    build_script:
      - yarn build
    test_script:
      - yarn test
  -
    matrix:
      only:
        - job_name: TestNodeJS14

    build_script:
      - yarn build
    before_test:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
    test_script:
      - yarn test:report
    after_test:
      - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
      - sh: |
          if [ "$APPVEYOR_PULL_REQUEST_NUMBER" = "" ]; then
              ./cc-test-reporter after-build -r ${CC_TEST_REPORTER_ID}
          fi

  - matrix:
      only:
        - APPVEYOR_PULL_REQUEST_NUMBER: ''
        - job_name: Deploy
        - branch: master
    build_script:
      - yarn build
    deploy_script:
      - npx -p @qiwi/semrel-toolkit multi-semrel
